export const ports = [
  { label: 'Shanghai', value: 'CNSHA', country: 'China', region: 'Asia' },
  { label: 'Singapore', value: 'SGSIN', country: 'Singapore', region: 'Asia' },
  { label: 'Ningbo-Zhoushan', value: 'CNNGB', country: 'China', region: 'Asia' },
  { label: 'Shenzhen', value: 'CNSZN', country: 'China', region: 'Asia' },
  { label: 'Guangzhou', value: 'CNCAN', country: 'China', region: 'Asia' },
  { label: 'Busan', value: 'KRPUS', country: 'South Korea', region: 'Asia' },
  { label: 'Hong Kong', value: 'HKHKG', country: 'Hong Kong', region: 'Asia' },
  { label: 'Qingdao', value: 'CNTAO', country: 'China', region: 'Asia' },
  { label: 'Tianjin', value: 'CNTSN', country: 'China', region: 'Asia' },
  { label: 'Rotterdam', value: 'NLRTM', country: 'Netherlands', region: 'Europe' },
  { label: 'Port Klang', value: 'MYPKG', country: 'Malaysia', region: 'Asia' },
  { label: 'Antwerp', value: 'BEANR', country: 'Belgium', region: 'Europe' },
  { label: 'Xiamen', value: 'CNXMN', country: 'China', region: 'Asia' },
  { label: 'Kaohsiung', value: 'TWKHH', country: 'Taiwan', region: 'Asia' },
  { label: 'Dalian', value: 'CNDLC', country: 'China', region: 'Asia' },
  { label: 'Los Angeles', value: 'USLAX', country: 'United States', region: 'North America' },
  { label: 'Hamburg', value: 'DEHAM', country: 'Germany', region: 'Europe' },
  { label: 'Tanjung Pelepas', value: 'MYTPP', country: 'Malaysia', region: 'Asia' },
  { label: 'Long Beach', value: 'USLGB', country: 'United States', region: 'North America' },
  { label: 'New York/New Jersey', value: 'USNYC', country: 'United States', region: 'North America' },
  { label: 'Laem Chabang', value: 'THLCH', country: 'Thailand', region: 'Asia' },
  { label: 'Tanjung Priok', value: 'IDJKT', country: 'Indonesia', region: 'Asia' },
  { label: 'Bremen/Bremerhaven', value: 'DEBRV', country: 'Germany', region: 'Europe' },
  { label: 'Yingkou', value: 'CNYKV', country: 'China', region: 'Asia' },
  { label: 'Algeciras', value: 'ESALG', country: 'Spain', region: 'Europe' },
  { label: 'Colombo', value: 'LKCMB', country: 'Sri Lanka', region: 'Asia' },
  { label: 'Durban', value: 'ZADUR', country: 'South Africa', region: 'Africa' },
  { label: 'Savannah', value: 'USSAV', country: 'United States', region: 'North America' },
  { label: 'Piraeus', value: 'GRPIR', country: 'Greece', region: 'Europe' },
  { label: 'Jeddah', value: 'SAJED', country: 'Saudi Arabia', region: 'Middle East' },
  { label: 'Le Havre', value: 'FRLEH', country: 'France', region: 'Europe' },
  { label: 'Valencia', value: 'ESVLC', country: 'Spain', region: 'Europe' },
  { label: 'Ho Chi Minh City', value: 'VNSGN', country: 'Vietnam', region: 'Asia' },
  { label: 'Jawaharlal Nehru', value: 'INNSA', country: 'India', region: 'Asia' },
  { label: 'Felixstowe', value: 'GBFXT', country: 'United Kingdom', region: 'Europe' },
  { label: 'Suez Canal', value: 'EGSUV', country: 'Egypt', region: 'Africa' },
  { label: 'Tangier Med', value: 'MATNG', country: 'Morocco', region: 'Africa' },
  { label: 'Charleston', value: 'USCHS', country: 'United States', region: 'North America' },
  { label: 'Keelung', value: 'TWKEL', country: 'Taiwan', region: 'Asia' },
  { label: 'Mundra', value: 'INMUN', country: 'India', region: 'Asia' },
  { label: 'Kobe', value: 'JPUKB', country: 'Japan', region: 'Asia' },
  { label: 'Nagoya', value: 'JPNGO', country: 'Japan', region: 'Asia' },
  { label: 'Yokohama', value: 'JPYOK', country: 'Japan', region: 'Asia' },
  { label: 'Norfolk', value: 'USORF', country: 'United States', region: 'North America' },
  { label: 'Lianyungang', value: 'CNLYG', country: 'China', region: 'Asia' },
  { label: 'Zeebrugge', value: 'BEZEE', country: 'Belgium', region: 'Europe' },
  { label: 'Barcelona', value: 'ESBCN', country: 'Spain', region: 'Europe' },
  { label: 'Constanta', value: 'ROCND', country: 'Romania', region: 'Europe' },
  { label: 'Vancouver', value: 'CAVAN', country: 'Canada', region: 'North America' },
  { label: 'Gioia Tauro', value: 'ITGIT', country: 'Italy', region: 'Europe' },
  { label: 'Tacoma', value: 'USTAC', country: 'United States', region: 'North America' },
  { label: 'Manila', value: 'PHMNL', country: 'Philippines', region: 'Asia' },
  { label: 'Salalah', value: 'OMSLL', country: 'Oman', region: 'Middle East' },
  { label: 'Gwangyang', value: 'KRKUV', country: 'South Korea', region: 'Asia' },
  { label: 'Haifa', value: 'ILHFA', country: 'Israel', region: 'Middle East' },
  { label: 'Tokyo', value: 'JPTYO', country: 'Japan', region: 'Asia' },
  { label: 'Genoa', value: 'ITGOA', country: 'Italy', region: 'Europe' },
  { label: 'Chittagong', value: 'BDCGP', country: 'Bangladesh', region: 'Asia' },
  { label: 'Sydney', value: 'AUSYD', country: 'Australia', region: 'Oceania' },
  { label: 'Melbourne', value: 'AUMEL', country: 'Australia', region: 'Oceania' },
  { label: 'Ashdod', value: 'ILASD', country: 'Israel', region: 'Middle East' },
  { label: 'Montreal', value: 'CAMTR', country: 'Canada', region: 'North America' },
  { label: 'Santos', value: 'BRSSZ', country: 'Brazil', region: 'South America' },
  { label: 'Marseille', value: 'FRMRS', country: 'France', region: 'Europe' },
  { label: 'Karachi', value: 'PKKHI', country: 'Pakistan', region: 'Asia' },
  { label: 'King Abdullah', value: 'SAKAB', country: 'Saudi Arabia', region: 'Middle East' },
  { label: 'Oakland', value: 'USOAK', country: 'United States', region: 'North America' },
  { label: 'Dammam', value: 'SADAM', country: 'Saudi Arabia', region: 'Middle East' },
  { label: 'La Spezia', value: 'ITLSP', country: 'Italy', region: 'Europe' },
  { label: 'Gothenburg', value: 'SEGOT', country: 'Sweden', region: 'Europe' },
  { label: 'Copenhagen', value: 'DKCPH', country: 'Denmark', region: 'Europe' },
  { label: 'Lisbon', value: 'PTLIS', country: 'Portugal', region: 'Europe' },
  { label: 'Miami', value: 'USMIA', country: 'United States', region: 'North America' },
  { label: 'Houston', value: 'USHOU', country: 'United States', region: 'North America' },
  { label: 'Seattle', value: 'USSEA', country: 'United States', region: 'North America' },
  { label: 'Veracruz', value: 'MXVER', country: 'Mexico', region: 'North America' },
  { label: 'Manzanillo', value: 'MXMAN', country: 'Mexico', region: 'North America' },
  { label: 'Callao', value: 'PECLL', country: 'Peru', region: 'South America' },
  { label: 'Valparaiso', value: 'CLVAP', country: 'Chile', region: 'South America' },
  { label: 'Buenos Aires', value: 'ARBUE', country: 'Argentina', region: 'South America' },
  { label: 'Rio de Janeiro', value: 'BRRIO', country: 'Brazil', region: 'South America' },
  { label: 'Paranagua', value: 'BRPNG', country: 'Brazil', region: 'South America' },
  { label: 'Itajai', value: 'BRITJ', country: 'Brazil', region: 'South America' },
  { label: 'Kingston', value: 'JMKIN', country: 'Jamaica', region: 'Caribbean' },
  { label: 'Freeport', value: 'BSFPO', country: 'Bahamas', region: 'Caribbean' },
  { label: 'Colon', value: 'PACRZ', country: 'Panama', region: 'Central America' },
  { label: 'Balboa', value: 'PABAL', country: 'Panama', region: 'Central America' },
  { label: 'Caucedo', value: 'DOCAU', country: 'Dominican Republic', region: 'Caribbean' },
  { label: 'San Juan', value: 'PRSJU', country: 'Puerto Rico', region: 'Caribbean' },
  { label: 'Cartagena', value: 'COCTG', country: 'Colombia', region: 'South America' },
  { label: 'Cape Town', value: 'ZACPT', country: 'South Africa', region: 'Africa' },
  { label: 'Lagos', value: 'NGLOS', country: 'Nigeria', region: 'Africa' },
  { label: 'Abidjan', value: 'CIABJ', country: 'Ivory Coast', region: 'Africa' },
  { label: 'Casablanca', value: 'MACAS', country: 'Morocco', region: 'Africa' },
  { label: 'Alexandria', value: 'EGALY', country: 'Egypt', region: 'Africa' },
  { label: 'Damietta', value: 'EGDMH', country: 'Egypt', region: 'Africa' },
  { label: 'Sokhna', value: 'EGSKH', country: 'Egypt', region: 'Africa' },
  { label: 'Djibouti', value: 'DJJIB', country: 'Djibouti', region: 'Africa' },
  { label: 'Mombasa', value: 'KEMBA', country: 'Kenya', region: 'Africa' },
  { label: 'Dar es Salaam', value: 'TZDAR', country: 'Tanzania', region: 'Africa' },
  { label: 'Maputo', value: 'MZMPM', country: 'Mozambique', region: 'Africa' },
  { label: 'Port Said', value: 'EGPSD', country: 'Egypt', region: 'Africa' },
  { label: 'Tema', value: 'GHTEM', country: 'Ghana', region: 'Africa' },
  { label: 'Aqaba', value: 'JOAQJ', country: 'Jordan', region: 'Middle East' },
  { label: 'Kuwait', value: 'KWKWI', country: 'Kuwait', region: 'Middle East' },
  { label: 'Doha', value: 'QADOH', country: 'Qatar', region: 'Middle East' },
  { label: 'Abu Dhabi', value: 'AEAUH', country: 'UAE', region: 'Middle East' },
  { label: 'Dubai', value: 'AEDXB', country: 'UAE', region: 'Middle East' },
  // Additional 100 major ports
  { label: 'Sharjah', value: 'AEAJM', country: 'UAE', region: 'Middle East' },
  { label: 'Fujairah', value: 'AEFUJ', country: 'UAE', region: 'Middle East' },
  { label: 'Ras Al Khaimah', value: 'AERKT', country: 'UAE', region: 'Middle East' },
  { label: 'Bandar Abbas', value: 'IRBND', country: 'Iran', region: 'Middle East' },
  { label: 'Chabahar', value: 'IRCHB', country: 'Iran', region: 'Middle East' },
  { label: 'Khorramshahr', value: 'IRKHO', country: 'Iran', region: 'Middle East' },
  { label: 'Bushehr', value: 'IRBUZ', country: 'Iran', region: 'Middle East' },
  { label: 'Bandar Mahshahr', value: 'IRMAH', country: 'Iran', region: 'Middle East' },
  { label: 'Mumbai', value: 'INBOM', country: 'India', region: 'Asia' },
  { label: 'Chennai', value: 'INMAA', country: 'India', region: 'Asia' },
  { label: 'Kolkata', value: 'INCCU', country: 'India', region: 'Asia' },
  { label: 'Cochin', value: 'INCOK', country: 'India', region: 'Asia' },
  { label: 'Tuticorin', value: 'INTUT', country: 'India', region: 'Asia' },
  { label: 'Visakhapatnam', value: 'INVTZ', country: 'India', region: 'Asia' },
  { label: 'Paradip', value: 'INPAP', country: 'India', region: 'Asia' },
  { label: 'Kandla', value: 'INKDL', country: 'India', region: 'Asia' },
  { label: 'Haldia', value: 'INHLD', country: 'India', region: 'Asia' },
  { label: 'Marmagao', value: 'INMRM', country: 'India', region: 'Asia' },
  { label: 'Mangalore', value: 'INMNG', country: 'India', region: 'Asia' },
  { label: 'Port Blair', value: 'INPBR', country: 'India', region: 'Asia' },
  { label: 'Ennore', value: 'INENR', country: 'India', region: 'Asia' },
  { label: 'Kakinada', value: 'INKAK', country: 'India', region: 'Asia' },
  { label: 'Galle', value: 'LKGAL', country: 'Sri Lanka', region: 'Asia' },
  { label: 'Hambantota', value: 'LKHRI', country: 'Sri Lanka', region: 'Asia' },
  { label: 'Trincomalee', value: 'LKTCM', country: 'Sri Lanka', region: 'Asia' },
  { label: 'Yangon', value: 'MMRGN', country: 'Myanmar', region: 'Asia' },
  { label: 'Thilawa', value: 'MMTHI', country: 'Myanmar', region: 'Asia' },
  { label: 'Sittwe', value: 'MMSIT', country: 'Myanmar', region: 'Asia' },
  { label: 'Penang', value: 'MYPEN', country: 'Malaysia', region: 'Asia' },
  { label: 'Johor', value: 'MYJHR', country: 'Malaysia', region: 'Asia' },
  { label: 'Kuantan', value: 'MYKUA', country: 'Malaysia', region: 'Asia' },
  { label: 'Bintulu', value: 'MYBTU', country: 'Malaysia', region: 'Asia' },
  { label: 'Kota Kinabalu', value: 'MYBKI', country: 'Malaysia', region: 'Asia' },
  { label: 'Kuching', value: 'MYKCH', country: 'Malaysia', region: 'Asia' },
  { label: 'Labuan', value: 'MYLBN', country: 'Malaysia', region: 'Asia' },
  { label: 'Belawan', value: 'IDBLW', country: 'Indonesia', region: 'Asia' },
  { label: 'Palembang', value: 'IDPLM', country: 'Indonesia', region: 'Asia' },
  { label: 'Surabaya', value: 'IDSUB', country: 'Indonesia', region: 'Asia' },
  { label: 'Semarang', value: 'IDSMG', country: 'Indonesia', region: 'Asia' },
  { label: 'Makassar', value: 'IDMKS', country: 'Indonesia', region: 'Asia' },
  { label: 'Balikpapan', value: 'IDBPN', country: 'Indonesia', region: 'Asia' },
  { label: 'Banjarmasin', value: 'IDBJM', country: 'Indonesia', region: 'Asia' },
  { label: 'Pontianak', value: 'IDPNK', country: 'Indonesia', region: 'Asia' },
  { label: 'Batam', value: 'IDBTM', country: 'Indonesia', region: 'Asia' },
  { label: 'Cilacap', value: 'IDCLP', country: 'Indonesia', region: 'Asia' },
  { label: 'Phuket', value: 'THPKT', country: 'Thailand', region: 'Asia' },
  { label: 'Map Ta Phut', value: 'THMTP', country: 'Thailand', region: 'Asia' },
  { label: 'Songkhla', value: 'THSGK', country: 'Thailand', region: 'Asia' },
  { label: 'Sattahip', value: 'THSTH', country: 'Thailand', region: 'Asia' },
  { label: 'Cai Mep', value: 'VNCMP', country: 'Vietnam', region: 'Asia' },
  { label: 'Hai Phong', value: 'VNHPH', country: 'Vietnam', region: 'Asia' },
  { label: 'Da Nang', value: 'VNDAD', country: 'Vietnam', region: 'Asia' },
  { label: 'Qui Nhon', value: 'VNQNH', country: 'Vietnam', region: 'Asia' },
  { label: 'Nha Trang', value: 'VNNHA', country: 'Vietnam', region: 'Asia' },
  { label: 'Can Tho', value: 'VNVCA', country: 'Vietnam', region: 'Asia' },
  { label: 'Cam Ranh', value: 'VNCAM', country: 'Vietnam', region: 'Asia' },
  { label: 'Subic Bay', value: 'PHSFS', country: 'Philippines', region: 'Asia' },
  { label: 'Batangas', value: 'PHBTG', country: 'Philippines', region: 'Asia' },
  { label: 'Cebu', value: 'PHCEB', country: 'Philippines', region: 'Asia' },
  { label: 'Davao', value: 'PHDVO', country: 'Philippines', region: 'Asia' },
  { label: 'Iloilo', value: 'PHILO', country: 'Philippines', region: 'Asia' },
  { label: 'Cagayan de Oro', value: 'PHCGO', country: 'Philippines', region: 'Asia' },
  { label: 'General Santos', value: 'PHGSC', country: 'Philippines', region: 'Asia' },
  { label: 'Zamboanga', value: 'PHZMB', country: 'Philippines', region: 'Asia' },
  { label: 'Taichung', value: 'TWTXG', country: 'Taiwan', region: 'Asia' },
  { label: 'Taoyuan', value: 'TWTPE', country: 'Taiwan', region: 'Asia' },
  { label: 'Hualien', value: 'TWHUN', country: 'Taiwan', region: 'Asia' },
  { label: 'Anping', value: 'TWANP', country: 'Taiwan', region: 'Asia' },
  { label: 'Ulsan', value: 'KRUSN', country: 'South Korea', region: 'Asia' },
  { label: 'Incheon', value: 'KRICN', country: 'South Korea', region: 'Asia' },
  { label: 'Mokpo', value: 'KRMPO', country: 'South Korea', region: 'Asia' },
  { label: 'Masan', value: 'KRMSN', country: 'South Korea', region: 'Asia' },
  { label: 'Pohang', value: 'KRPOH', country: 'South Korea', region: 'Asia' },
  { label: 'Gunsan', value: 'KRKUV', country: 'South Korea', region: 'Asia' },
  { label: 'Jeju', value: 'KRCEJ', country: 'South Korea', region: 'Asia' },
  { label: 'Osaka', value: 'JPOSA', country: 'Japan', region: 'Asia' },
  { label: 'Chiba', value: 'JPNRT', country: 'Japan', region: 'Asia' },
  { label: 'Kawasaki', value: 'JPKAW', country: 'Japan', region: 'Asia' },
  { label: 'Kitakyushu', value: 'JPKTQ', country: 'Japan', region: 'Asia' },
  { label: 'Hakata', value: 'JPFUK', country: 'Japan', region: 'Asia' },
  { label: 'Niigata', value: 'JPKIJ', country: 'Japan', region: 'Asia' },
  { label: 'Sendai', value: 'JPSDT', country: 'Japan', region: 'Asia' },
  { label: 'Hakodate', value: 'JPHKD', country: 'Japan', region: 'Asia' },
  { label: 'Otaru', value: 'JPOTR', country: 'Japan', region: 'Asia' },
  { label: 'Shimizu', value: 'JPSHZ', country: 'Japan', region: 'Asia' },
  { label: 'Sakai', value: 'JPSKI', country: 'Japan', region: 'Asia' },
  { label: 'Wakayama', value: 'JPWAY', country: 'Japan', region: 'Asia' },
  { label: 'Vladivostok', value: 'RUVVO', country: 'Russia', region: 'Asia' },
  { label: 'Nakhodka', value: 'RUNHK', country: 'Russia', region: 'Asia' },
  { label: 'Vanino', value: 'RUVNN', country: 'Russia', region: 'Asia' },
  { label: 'Magadan', value: 'RUMGD', country: 'Russia', region: 'Asia' },
  { label: 'Petropavlovsk', value: 'RUPKC', country: 'Russia', region: 'Asia' },
  { label: 'Novorossiysk', value: 'RUNVS', country: 'Russia', region: 'Europe' },
  { label: 'St. Petersburg', value: 'RULED', country: 'Russia', region: 'Europe' },
  { label: 'Kaliningrad', value: 'RUKGD', country: 'Russia', region: 'Europe' },
  { label: 'Murmansk', value: 'RUMMK', country: 'Russia', region: 'Europe' },
  { label: 'Arkhangelsk', value: 'RUARH', country: 'Russia', region: 'Europe' },
  { label: 'Riga', value: 'LVRIX', country: 'Latvia', region: 'Europe' },
  { label: 'Tallinn', value: 'EETLL', country: 'Estonia', region: 'Europe' },
  { label: 'Helsinki', value: 'FIHEL', country: 'Finland', region: 'Europe' },
  { label: 'Stockholm', value: 'SESTO', country: 'Sweden', region: 'Europe' },
  { label: 'Oslo', value: 'NOOSL', country: 'Norway', region: 'Europe' },
  { label: 'Bergen', value: 'NOBGN', country: 'Norway', region: 'Europe' },
  { label: 'Stavanger', value: 'NOSVG', country: 'Norway', region: 'Europe' },
  { label: 'Trondheim', value: 'NOTRD', country: 'Norway', region: 'Europe' },
  { label: 'Reykjavik', value: 'ISREY', country: 'Iceland', region: 'Europe' },
];
