import { resolve } from 'path';
import { defineConfig } from 'vite';
import copy from 'rollup-plugin-copy';

export default defineConfig({
  build: {
    outDir: '../dist/lighthouse',
    rollupOptions: {
      input: {
        'mc-avatar': '/packages/mc-avatar/lighthouse/index.html',
        'mc-button-group-item': '/packages/mc-button-group-item/lighthouse/index.html',
        'mc-button-group': '/packages/mc-button-group/lighthouse/index.html',
        'mc-button': '/packages/mc-button/lighthouse/index.html',
        'mc-calendar': '/packages/mc-calendar/lighthouse/index.html',
        'mc-card': '/packages/mc-card/lighthouse/index.html',
        'mc-checkbox-group': '/packages/mc-checkbox-group/lighthouse/index.html',
        'mc-checkbox': '/packages/mc-checkbox/lighthouse/index.html',
        'mc-date-range': '/packages/mc-date-range/lighthouse/index.html',
        'mc-error': '/packages/mc-error/lighthouse/index.html',
        'mc-file-upload': '/packages/mc-file-upload/lighthouse/index.html',
        'mc-hint': '/packages/mc-hint/lighthouse/index.html',
        'mc-icon': '/packages/mc-icon/lighthouse/index.html',
        'mc-input-date': '/packages/mc-input-date/lighthouse/index.html',
        'mc-input-time': '/packages/mc-input-time/lighthouse/index.html',
        'mc-input': '/packages/mc-input/lighthouse/index.html',
        'mc-label': '/packages/mc-label/lighthouse/index.html',
        'mc-list-item': '/packages/mc-list-item/lighthouse/index.html',
        'mc-list': '/packages/mc-list/lighthouse/index.html',
        'mc-loading-indicator': '/packages/mc-loading-indicator/lighthouse/index.html',
        'mc-menu': '/packages/mc-menu/lighthouse/index.html',
        'mc-modal': '/packages/mc-modal/lighthouse/index.html',
        'mc-month-year-picker': '/packages/mc-month-year-picker/lighthouse/index.html',
        'mc-multi-select': '/packages/mc-multi-select/lighthouse/index.html',
        'mc-notification': '/packages/mc-notification/lighthouse/index.html',
        'mc-number-stepper': '/packages/mc-number-stepper/lighthouse/index.html',
        'mc-option': '/packages/mc-option/lighthouse/index.html',
        'mc-pagination': '/packages/mc-pagination/lighthouse/index.html',
        'mc-picker-item': '/packages/mc-picker-item/lighthouse/index.html',
        'mc-picker': '/packages/mc-picker/lighthouse/index.html',
        'mc-popover': '/packages/mc-popover/lighthouse/index.html',
        'mc-radio-group': '/packages/mc-radio-group/lighthouse/index.html',
        'mc-radio': '/packages/mc-radio/lighthouse/index.html',
        'mc-segmented-control-item': '/packages/mc-segmented-control-item/lighthouse/index.html',
        'mc-segmented-control': '/packages/mc-segmented-control/lighthouse/index.html',
        'mc-select-native': '/packages/mc-select-native/lighthouse/index.html',
        'mc-select': '/packages/mc-select/lighthouse/index.html',
        'mc-switch-group': '/packages/mc-switch-group/lighthouse/index.html',
        'mc-switch': '/packages/mc-switch/lighthouse/index.html',
        'mc-tab-bar': '/packages/mc-tab-bar/lighthouse/index.html',
        'mc-tab': '/packages/mc-tab/lighthouse/index.html',
        'mc-table': '/packages/mc-table/lighthouse/index.html',
        'mc-tag': '/packages/mc-tag/lighthouse/index.html',
        'mc-text-and-icon': '/packages/mc-text-and-icon/lighthouse/index.html',
        'mc-textarea': '/packages/mc-textarea/lighthouse/index.html',
        'mc-time-picker': '/packages/mc-time-picker/lighthouse/index.html',
        'mc-toast': '/packages/mc-toast/lighthouse/index.html',
        'mc-tooltip': '/packages/mc-tooltip/lighthouse/index.html',
        'mc-typeahead': '/packages/mc-typeahead/lighthouse/index.html',
        'mc-step-indicator-item': '/packages/mc-step-indicator-item/lighthouse/index.html',
        'mc-step-indicator': '/packages/mc-step-indicator/lighthouse/index.html',
        'mc-dialog': '/packages/mc-dialog/lighthouse/index.html',
        'mc-link-button': '/packages/mc-link-button/lighthouse/index.html',
        'mc-drawer': '/packages/mc-drawer/lighthouse/index.html',
        'mc-top-bar': '/packages/mc-top-bar/lighthouse/index.html',
        'mc-side-bar': '/packages/mc-side-bar/lighthouse/index.html',
        'mc-theme-switch': '/packages/mc-theme-switch/lighthouse/index.html',
'mc-progress-indicator': '/packages/mc-progress-indicator/lighthouse/index.html',
'mc-badge': '/packages/mc-badge/lighthouse/index.html',
'mc-typeahead-multi-select': '/packages/mc-typeahead-multi-select/lighthouse/index.html',
'mc-input-group': '/packages/mc-input-group/lighthouse/index.html',
//%%COMPONENT_NAME%%
      },
    },
  },
  plugins: [
    copy({
      targets: [
        {
          src: 'node_modules/@maersk-global/icons/**/*',
          dest: 'dist/lighthouse/assets/',
        },
      ],
      flatten: false,
      hook: 'writeBundle',
      copySync: true,
    }),
  ],
  resolve: {
    alias: {
      '@maersk-global/mds-components-utils/host/host.styles.js':
        '/dist/packages/mds-components-utils/lib/host/host.styles.js',
      '@maersk-global/mds-components-utils': '/packages/mds-components-utils',
      '@maersk-global/mds-config': '/packages/mds-config',
      '@maersk-global/mds-design-tokens/maersk/light/css/design-tokens-px.css':
        '/dist/packages/mds-design-tokens/maersk/light/css/design-tokens-px.css',
      '@maersk-global/mds-design-tokens': '/dist/packages/mds-design-tokens',
      '@maersk-global/mds-components-core-button/src/lib/styles/mc-button.mixins.scss':
        './dist/packages/mds-components-core-button/src/lib/styles/mc-button.mixins.scss',
      '@maersk-global/mds-dev-utils': '/packages/mds-dev-utils',
      '@maersk-global/mds-foundations': '/packages/mds-foundations',
      '@maersk-global/mds-shared-types': '/packages/mds-shared-types/index.d.ts',
      '@maersk-global/mds-components-core-icon': '/packages/mc-icon/src/index.ts',
      '@maersk-global/mds-components-core-text-and-icon': '/packages/mc-text-and-icon/src/index.ts',
      '@maersk-global/mds-components-core-loading-indicator': '/packages/mc-loading-indicator/src/index.ts',
      '@maersk-global/mds-components-core-button': '/packages/mc-button/src/index.ts',
      '@maersk-global/mds-components-core-label': '/packages/mc-label/src/index.ts',
      '@maersk-global/mds-components-core-hint': '/packages/mc-hint/src/index.ts',
      '@maersk-global/mds-components-core-card': '/packages/mc-card/src/index.ts',
      '@maersk-global/mds-components-core-error': '/packages/mc-error/src/index.ts',
      '@maersk-global/mds-components-core-tag': '/packages/mc-tag/src/index.ts',
      '@maersk-global/mds-components-core-checkbox': '/packages/mc-checkbox/src/index.ts',
      '@maersk-global/mds-components-core-radio': '/packages/mc-radio/src/index.ts',
      '@maersk-global/mds-components-core-switch': '/packages/mc-switch/src/index.ts',
      '@maersk-global/mds-components-core-multi-choice-fieldset': '/packages/mc-multi-choice-fieldset/src/index.ts',
      '@maersk-global/mds-components-core-checkbox-group': '/packages/mc-checkbox-group/src/index.ts',
      '@maersk-global/mds-components-core-radio-group': '/packages/mc-radio-group/src/index.ts',
      '@maersk-global/mds-components-core-switch-group': '/packages/mc-switch-group/src/index.ts',
      '@maersk-global/mds-components-core-list-item': '/packages/mc-list-item/src/index.ts',
      '@maersk-global/mds-components-core-option': '/packages/mc-option/src/index.ts',
      '@maersk-global/mds-components-core-list': '/packages/mc-list/src/index.ts',
      '@maersk-global/mds-components-core-button-group-item': '/packages/mc-button-group-item/src/index.ts',
      '@maersk-global/mds-components-core-button-group': '/packages/mc-button-group/src/index.ts',
      '@maersk-global/mds-components-core-segmented-control-item': '/packages/mc-segmented-control-item/src/index.ts',
      '@maersk-global/mds-components-core-segmented-control': '/packages/mc-segmented-control/src/index.ts',
      '@maersk-global/mds-components-core-notification': '/packages/mc-notification/src/index.ts',
      '@maersk-global/mds-components-core-toast': '/packages/mc-toast/src/index.ts',
      '@maersk-global/mds-components-core-pagination': '/packages/mc-pagination/src/index.ts',
      '@maersk-global/mds-components-core-tab': '/packages/mc-tab/src/index.ts',
      '@maersk-global/mds-components-core-tab-bar': '/packages/mc-tab-bar/src/index.ts',
      '@maersk-global/mds-components-core-modal': '/packages/mc-modal/src/index.ts',
      '@maersk-global/mds-components-core-popover': '/packages/mc-popover/src/index.ts',
      '@maersk-global/mds-components-core-picker-item': '/packages/mc-picker-item/src/index.ts',
      '@maersk-global/mds-components-core-picker': '/packages/mc-picker/src/index.ts',
      '@maersk-global/mds-components-core-time-picker': '/packages/mc-time-picker/src/index.ts',
      '@maersk-global/mds-components-core-month-year-picker': '/packages/mc-month-year-picker/src/index.ts',
      '@maersk-global/mds-components-core-calendar': '/packages/mc-calendar/src/index.ts',
      '@maersk-global/mds-components-core-menu': '/packages/mc-menu/src/index.ts',
      '@maersk-global/mds-components-core-tooltip': '/packages/mc-tooltip/src/index.ts',
      '@maersk-global/mds-components-core-avatar': '/packages/mc-avatar/src/index.ts',
      '@maersk-global/mds-components-core-input': '/packages/mc-input/src/index.ts',
      '@maersk-global/mds-components-core-number-stepper': '/packages/mc-number-stepper/src/index.ts',
      '@maersk-global/mds-components-core-textarea': '/packages/mc-textarea/src/index.ts',
      '@maersk-global/mds-components-core-select-native': '/packages/mc-select-native/src/index.ts',
      '@maersk-global/mds-components-core-input-date': '/packages/mc-input-date/src/index.ts',
      '@maersk-global/mds-components-core-input-time': '/packages/mc-input-time/src/index.ts',
      '@maersk-global/mds-components-core-date-range': '/packages/mc-date-range/src/index.ts',
      '@maersk-global/mds-components-core-file-upload': '/packages/mc-file-upload/src/index.ts',
      '@maersk-global/mds-components-core-select': '/packages/mc-select/src/index.ts',
      '@maersk-global/mds-components-core-multi-select': '/packages/mc-multi-select/src/index.ts',
      '@maersk-global/mds-components-core-typeahead': '/packages/mc-typeahead/src/index.ts',
      '@maersk-global/mds-components-core-table': '/packages/mc-table/src/index.ts',
      '@maersk-global/mds-components-core-step-indicator-item': '/packages/mc-step-indicator-item/src/index.ts',
      '@maersk-global/mds-components-core-step-indicator': '/packages/mc-step-indicator/src/index.ts',
      '@maersk-global/mds-components-core-dialog': '/packages/mc-dialog/src/index.ts',
      'mc-link-button': '/packages/mc-link-button/lighthouse/index.html',
      '@maersk-global/mds-components-core-drawer': '/packages/mc-drawer/src/index.ts',
      '@maersk-global/mds-components-core-top-bar': '/packages/mc-top-bar/src/index.ts',
      '@maersk-global/mds-components-core-side-bar': '/packages/mc-side-bar/src/index.ts',
      '@maersk-global/mds-components-core-theme-switch': '/packages/mc-theme-switch/src/index.ts',
'@maersk-global/mds-components-core-progress-indicator': '/packages/mc-progress-indicator/src/index.ts',
'@maersk-global/mds-components-core-badge': '/packages/mc-badge/src/index.ts',
'@maersk-global/mds-components-core-typeahead-multi-select': '/packages/mc-typeahead-multi-select/src/index.ts',
'@maersk-global/mds-components-core-input-group': '/packages/mc-input-group/src/index.ts',
//%%COMPONENT_ALIAS%%
    },
  },
});
