import {
  name,
  hint,
  errormessage,
  invalid,
  label,
  hiddenlabel,
  placeholder,
  fit,
  labelposition,
  id,
  disabled,
  required,
  readonly,
  value,
  eventtype,
  width,
  autofocus,
} from '@maersk-global/mds-dev-utils';

export default {
  label: label('mc-textarea', 'Explanation'),
  hiddenlabel: hiddenlabel('Content'),
  placeholder: placeholder('Write short explanation'),
  hint: hint('mc-textarea'),
  fit,
  autofocus: autofocus('mc-textarea'),
  width: width('The width of the inner input container in percentage. If not provided the width will be `auto`.'),
  maxlength: {
    name: 'maxlength',
    type: { required: false },
    defaultValue: '',
    description:
      'Setting this property will activate a character counter and limit the number of characters that can be entered in the `textarea`',
    table: {
      category: 'Content',
      type: { summary: 'number' },
    },
    control: {
      type: 'number',
    },
  },
  rows: {
    name: 'rows',
    type: { required: false },
    defaultValue: 5,
    description: 'The height of the textarea will depend on the number of rows',
    table: {
      category: 'Style',
      type: { summary: 'number' },
      defaultValue: { summary: '5' },
    },
    control: {
      type: 'number',
    },
  },
  labelposition,
  id,
  name: name('explanation'),
  value: value(),
  invalid,
  errormessage: errormessage('mc-textarea'),
  disabled,
  readonly,
  required,
  input: eventtype('input'),
  focus: eventtype('focus'),
  blur: eventtype('blur'),
  click: eventtype('click'),
  keydown: eventtype('keydown'),
};
