export const states = [
  { display: 'pinned', label: '9', position: 'top', distance: 'small', accessibility: true },
  { display: 'pinned', label: '9', position: 'top', distance: 'medium', accessibility: false },
  { display: 'pinned', label: '9', position: 'top', distance: 'large', accessibility: false },
  { display: 'pinned', label: 'New', position: 'top', distance: 'small', accessibility: true },
  { display: 'pinned', label: 'New', position: 'top', distance: 'medium', accessibility: false },
  { display: 'pinned', label: 'New', position: 'top', distance: 'large', accessibility: false },
  { display: 'pinned', label: '9', position: 'bottom', distance: 'small', accessibility: false },
  { display: 'pinned', label: '9', position: 'bottom', distance: 'medium', accessibility: false },
  { display: 'pinned', label: '9', position: 'bottom', distance: 'large', accessibility: false },
  { display: 'pinned', label: 'New', position: 'bottom', distance: 'small', accessibility: false },
  { display: 'pinned', label: 'New', position: 'bottom', distance: 'medium', accessibility: false },
  { display: 'pinned', label: 'New', position: 'bottom', distance: 'large', accessibility: false },
  { display: 'inline', label: '9', position: 'left', accessibility: false },
  { display: 'inline', label: 'New', position: 'left', accessibility: false },
  { display: 'inline', label: '9', position: 'right', accessibility: false },
  { display: 'inline', label: 'New', position: 'right', accessibility: false },
];
