name: Push
on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - '!main'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up npm registry
        uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: https://npm.pkg.github.com/
          scope: '@maersk-global'
        env:
          NODE_AUTH_TOKEN: ${{secrets.GHCR_PULL_TOKEN}}

      - name: Cache dependencies
        uses: actions/cache@v4
        id: cache
        with:
          path: |
            ~/.cache/Cypress
            node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json', 'packages/**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json', 'packages/**/package-lock.json') }}

      - name: Install
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm i

      - name: Lint
        run: npx nx run-many --target=lint

      - name: Build packages
        run: npx nx run-many --target=build

      - name: Build metadata
        run: npx nx run-many --target=generate:metadata
