# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
registries:
  maersk-global:
    type: npm-registry
    url: https://npm.pkg.github.com/
    username: ${{ github.actor }}
    password: ${{secrets.GH_PACKAGES_READ_TOKEN}}
  github-maersk:
    type: git
    url: https://github.com
    username: dot-automation-member
    password: ${{secrets.EE_CHECKOUT_TOKEN}}
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    registries:
      - github-maersk
    schedule:
      interval: 'monthly'
    allow:
      # Allow only all explicitly defined dependencies.
      - dependency-type: 'direct'
    commit-message:
      prefix: 'chore'
      include: 'scope'
    open-pull-requests-limit: 2
    pull-request-branch-name:
      separator: '-'
    assignees:
      - 'aneta-kjeldsen'
      - 'marcin-sieradzki-maersk'
      - 'nataliasowa-maersk'

  - package-ecosystem: 'npm'
    directory: '/'
    registries:
      - maersk-global
    schedule:
      interval: 'monthly'
    allow:
      - dependency-type: 'direct'
    commit-message:
      prefix: 'chore'
      include: 'scope'
    open-pull-requests-limit: 5
    pull-request-branch-name:
      separator: '-'
    assignees:
      - 'aneta-kjeldsen'
      - 'marcin-sieradzki-maersk'
      - 'nataliasowa-maersk'
    groups:
      mds:
        patterns:
          - '@maersk-global/mds*'
      storybook:
        patterns:
          - '@storybook/*'
      nx:
        patterns:
          - '@nx/*'
          - 'nx'
      angular:
        patterns:
          - '@angular/*'
          - 'angular-devkit/*'
          - 'angular-eslint/*'
          - 'jest-preset-angular'
          - '@schematics/angular'
          - '@nx/angular'
      commit-lint:
        patterns:
          - '@commit-lint/*'
      typescript-eslint:
        patterns:
          - '@typescript-eslint/*'
          - '@nx/eslint-plugin'
