export const states = [
  { orientation: 'horizontal', state: 'pending', label: 'Label', accessibility: true },
  { orientation: 'horizontal', state: 'current', label: 'Label', accessibility: true },
  { orientation: 'horizontal', state: 'completed', label: 'Label', accessibility: true },
  { orientation: 'vertical', state: 'pending', label: 'Label', accessibility: false },
  { orientation: 'vertical', state: 'current', label: 'Label', accessibility: false },
  { orientation: 'vertical', state: 'completed', label: 'Label', accessibility: false },
  {
    orientation: 'horizontal',
    state: 'pending',
    slots: [{ content: `<span>Label as a slot</span>` }],
    accessibility: false,
  },
  {
    orientation: 'horizontal',
    state: 'current',
    slots: [{ content: `<span>Label as a slot</span>` }],
    accessibility: false,
  },
  {
    orientation: 'horizontal',
    state: 'completed',
    slots: [{ content: `<span>Label as a slot</span>` }],
    accessibility: false,
  },
  {
    orientation: 'vertical',
    state: 'pending',
    slots: [{ content: `<span>Label as a slot</span>` }],
    accessibility: false,
  },
  {
    orientation: 'vertical',
    state: 'current',
    slots: [{ content: `<span>Label as a slot</span>` }],
    accessibility: false,
  },
  {
    orientation: 'vertical',
    state: 'completed',
    slots: [{ content: `<span>Label as a slot</span>` }],
    accessibility: false,
  },
  { orientation: 'horizontal', state: 'pending', label: 'Label', icon: 'star', accessibility: false },
  { orientation: 'horizontal', state: 'current', label: 'Label', icon: 'star', accessibility: false },
  { orientation: 'horizontal', state: 'completed', label: 'Label', icon: 'star', accessibility: false },
  {
    orientation: 'vertical',
    state: 'pending',
    slots: [{ name: 'icon', content: `<span slot="icon"><mc-icon icon="clock"></mc-icon></span>` }],
    accessibility: false,
  },
  {
    orientation: 'vertical',
    state: 'current',
    slots: [{ name: 'icon', content: `<span slot="icon"><mc-icon icon="clock"></mc-icon></span>` }],
    accessibility: false,
  },
  {
    orientation: 'vertical',
    state: 'completed',
    slots: [{ name: 'icon', content: `<span slot="icon"><mc-icon icon="clock"></mc-icon></span>` }],
    accessibility: false,
  },
  {
    state: 'pending',
    appearance: 'default',
    accessibility: true,
  },
  { state: 'pending', appearance: 'warning', accessibility: true },
  { state: 'pending', appearance: 'error', accessibility: true },
  { state: 'current', appearance: 'warning', accessibility: true },
  { state: 'current', appearance: 'error', accessibility: true },
  { state: 'completed', appearance: 'warning', accessibility: true },
  { state: 'completed', appearance: 'error', accessibility: true },
];
