const { sassPlugin } = require('esbuild-sass-plugin');
const { minify } = require('csso');
const { minifyHTMLLiteralsPlugin } = require('./minify-html-plugin.cjs');
const typescriptDeclarationsPlugin = require('./typescript-declarations-plugin.cjs');

const alwaysExternal = [
  '@floating-ui/dom',
  '@lit-labs/observers',
  '@lit/react',
  '@lit/reactive-element',
  '@maersk-global/icons',
  '@maersk-global/mds-components-core-avatar',
  '@maersk-global/mds-components-core-button-group-item',
  '@maersk-global/mds-components-core-button-group',
  '@maersk-global/mds-components-core-button',
  '@maersk-global/mds-components-core-calendar',
  '@maersk-global/mds-components-core-card',
  '@maersk-global/mds-components-core-checkbox-group',
  '@maersk-global/mds-components-core-checkbox',
  '@maersk-global/mds-components-core-date-range',
  '@maersk-global/mds-components-core-error',
  '@maersk-global/mds-components-core-file-upload',
  '@maersk-global/mds-components-core-hint',
  '@maersk-global/mds-components-core-icon',
  '@maersk-global/mds-components-core-input-date',
  '@maersk-global/mds-components-core-input-time',
  '@maersk-global/mds-components-core-input',
  '@maersk-global/mds-components-core-label',
  '@maersk-global/mds-components-core-list-item',
  '@maersk-global/mds-components-core-list',
  '@maersk-global/mds-components-core-loading-indicator',
  '@maersk-global/mds-components-core-menu',
  '@maersk-global/mds-components-core-modal',
  '@maersk-global/mds-components-core-month-year-picker',
  '@maersk-global/mds-components-core-multi-choice-fieldset',
  '@maersk-global/mds-components-core-multi-select',
  '@maersk-global/mds-components-core-notification',
  '@maersk-global/mds-components-core-number-stepper',
  '@maersk-global/mds-components-core-option',
  '@maersk-global/mds-components-core-pagination',
  '@maersk-global/mds-components-core-picker-item',
  '@maersk-global/mds-components-core-picker',
  '@maersk-global/mds-components-core-popover',
  '@maersk-global/mds-components-core-radio-group',
  '@maersk-global/mds-components-core-radio',
  '@maersk-global/mds-components-core-segmented-control-item',
  '@maersk-global/mds-components-core-segmented-control',
  '@maersk-global/mds-components-core-select-native',
  '@maersk-global/mds-components-core-select',
  '@maersk-global/mds-components-core-switch-group',
  '@maersk-global/mds-components-core-switch',
  '@maersk-global/mds-components-core-tab-bar',
  '@maersk-global/mds-components-core-tab',
  '@maersk-global/mds-components-core-table',
  '@maersk-global/mds-components-core-tag',
  '@maersk-global/mds-components-core-text-and-icon',
  '@maersk-global/mds-components-core-textarea',
  '@maersk-global/mds-components-core-time-picker',
  '@maersk-global/mds-components-core-toast',
  '@maersk-global/mds-components-core-tooltip',
  '@maersk-global/mds-components-core-typeahead',
  '@maersk-global/mds-components-core',
  '@maersk-global/mds-components-utils',
  '@maersk-global/mds-config',
  '@maersk-global/mds-design-tokens',
  '@maersk-global/mds-foundations',
  '@tanstack',
  'animejs',
  'dayjs',
  'imask',
  'lit-element',
  'lit-html',
  'lit',
  'react-dom',
  'react',
  '@maersk-global/mds-components-core-step-indicator-item',
  '@maersk-global/mds-components-core-step-indicator',
  '@maersk-global/mds-components-core-dialog',
  '@maersk-global/mds-components-core-link-button',
  '@maersk-global/mds-components-core-drawer',
  '@maersk-global/mds-components-core-top-bar',
  '@maersk-global/mds-components-core-side-bar',
  '@maersk-global/mds-components-core-theme-switch',
'@maersk-global/mds-components-core-progress-indicator',
'@maersk-global/mds-components-core-badge',
'@maersk-global/mds-components-core-typeahead-multi-select',
'@maersk-global/mds-components-core-input-group',
//%%COMPONENT_ESBUILD_ALWAYS_EXTERNAL%%
];
/** @type {import('esbuild').BuildOptions}  */
module.exports = {
  format: 'esm',
  metafile: true,
  treeShaking: true,
  sourcemap: 'external',
  color: true,
  bundle: true,
  splitting: true,
  platform: 'browser',
  define: {
    // Inner double quotes are required,
    // otherwise 'production' will be considered as an identifier instead!
    'process.env.NODE_ENV': '"production"',
  },
  /*
   * We don't bundle external dependencies in the unbundled build. This ensures we ship bare module specifiers,
   * allowing end users to better optimize when using a bundler.
   * We never bundle react though! (Only packages that ship ESM can be external.)
   */
  external: [...alwaysExternal],
  plugins: [
    sassPlugin({
      type: 'lit-css',
      transform: (source) => minify(source).css,
    }),
    minifyHTMLLiteralsPlugin(),
    typescriptDeclarationsPlugin(),
  ],
  logLevel: 'debug',
};
